### ISSUE TITLE
Must use import to load ES Module: `.../node_modules/@polkadot/x-bigint/shim.js`

### ISSUE THREAD

**Issue by shekohex** [polkadot-js/common#1418]
Hello, I'm using Jest & Typescript, and it does not work because of this error:

```bash
yarn test
```

```log
yarn run v1.22.17
$ cross-env NODE_OPTIONS=--experimental-vm-modules jest --forceExit --runInBand
(node:28187) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  ./dummy.test.ts
(node:28187) V8: /home/shady/github/webb-tools/relayer/tests/node_modules/ganache/dist/node/0.js:2 Linking failure in asm.js: Unexpected stdlib member
 FAIL  ./evmTransactionRelayer.test.ts
  ● Test suite failed to run

    Must use import to load ES Module: /home/shady/github/webb-tools/relayer/tests/node_modules/@polkadot/x-bigint/shim.js

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
      at Object.<anonymous> (node_modules/@polkadot/util-crypto/cryptoInit.cjs:3:1)
      at Object.<anonymous> (node_modules/@polkadot/util-crypto/bundle.cjs:16:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.566 s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
error Command failed with exit code 1.
```

* My `jest.config.mjs`
```js
export default {
  extensionsToTreatAsEsm: ['.ts'],
  transformIgnorePatterns: [
    '\\.pnp\\.[^\\/]+$',
    '/node_modules/(?!@polkadot|@babel/runtime/helpers/esm/)',
  ],
};
```
* My `babel.config.mjs`
```js
export default {
  presets: [
    ['@babel/preset-env', { targets: { node: 'current' } }],
    '@babel/preset-typescript',
  ],
  plugins: [],
};
```

### Meta

```
node: v17.5.0
jest: ^27.5.1
@babel/core: ^7.17.5
@polkadt/api: ^7.10.1
typescript: ^4.6.2
```

> Full Code could be found here: https://github.com/webb-tools/relayer/tree/4ecfda7e78b6240b4e2f4885ff3fdc8ffaafbc95/tests

**Comment by jacogr** [comment]
Please do a search of the issues, there has been a lot written and asked about Jest.

**Comment by shekohex** [comment]
I did, I've been trying different examples and solutions but none of them are working as expected. but I will try again to find a similar issue. if I found a solution there I will link it here and close the issue.

**Comment by shekohex** [comment]
Well, I managed to solve it, thanks to this comment here https://github.com/polkadot-js/api/issues/4292#issuecomment-988005913

So, for anyone who will see this issue in the future, you have to do this hack like so:
```js
export default {
  preset: 'ts-jest/presets/default-esm',
  globals: {
    'ts-jest': {
      useESM: true,
    },
  },
  extensionsToTreatAsEsm: ['.ts'],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@polkadot/rpc-core/(.*).js$': '@polkadot/rpc-core/$1.js',
    '^@polkadot/rpc-core$': '@polkadot/rpc-core/index.js',
    '^@polkadot/rpc-provider/(.*).js$': '@polkadot/rpc-provider/$1.js',
    '^@polkadot/rpc-provider$': '@polkadot/rpc-provider/index.js',
    '^@polkadot/rpc-augment/(.*).js$': '@polkadot/rpc-augment/$1.js',
    '^@polkadot/rpc-augment$': '@polkadot/rpc-augment/index.js',
    '^@polkadot/keyring/(.*).js$': '@polkadot/keyring/$1.js',
    '^@polkadot/keyring$': '@polkadot/keyring/index.js',
    '^@polkadot/api/(.*).js$': '@polkadot/api/$1.js',
    '^@polkadot/api$': '@polkadot/api/index.js',
    '^@polkadot/api-derive/(.*).js$': '@polkadot/api-derive/$1.js',
    '^@polkadot/api-derive$': '@polkadot/api-derive/index.js',
    '^@polkadot/metadata/(.*)/(.*)': '@polkadot/metadata/$1/$2.js',
    '^@polkadot/metadata/decorate$': '@polkadot/metadata/decorate/index.js',
    '^@polkadot/metadata/(.*)': '@polkadot/metadata/$1.js',
    '^@polkadot/metadata$': '@polkadot/metadata/index.js',
    '^@polkadot/networks/(.*).js$': '@polkadot/networks/$1.js',
    '^@polkadot/networks/(.*)': '@polkadot/networks/$1.js',
    '^@polkadot/networks$': '@polkadot/networks/index.js',
    '^@polkadot/types/codec$': '@polkadot/types/codec/index.js',
    '^@polkadot/types/primitive$': '@polkadot/types/primitive/index.js',
    '^@polkadot/types/augment$': '@polkadot/types/augment/index.js',
    '^@polkadot/types/metadata$': '@polkadot/types/metadata/index.js',
    '^@polkadot/types/metadata/decorate$':
      '@polkadot/types/metadata/decorate/index.js',
    '^@polkadot/types/types$': '@polkadot/types/types/index.js',
    '^@polkadot/types/(.*)/(.*)': '@polkadot/types/$1/$2.js',
    '^@polkadot/types/(.*).js$': '@polkadot/types/$1.js',
    '^@polkadot/types/(.*)': '@polkadot/types/$1.js',
    '^@polkadot/types$': '@polkadot/types/index.js',
    '^@polkadot/types-known$': '@polkadot/types-known/index.js',
    '^@polkadot/types-create$': '@polkadot/types-create/index.js',
    '^@polkadot/types-codec$': '@polkadot/types-codec/index.js',
    '^@polkadot/util/(.*).js$': '@polkadot/util/$1.js',
    '^@polkadot/util$': '@polkadot/util/index.js',
    '^@polkadot/util-crypto$': '@polkadot/util-crypto/index.js',
    '^@polkadot/wasm-crypto$': '@polkadot/wasm-crypto/index.js',
    '^@polkadot/wasm-crypto-asmjs/(.*)': '@polkadot/wasm-crypto-asmjs/$1.js',
    '^@polkadot/wasm-crypto-asmjs$': '@polkadot/wasm-crypto-asmjs/empty.js',
    '^@polkadot/wasm-crypto-wasm/(.*)': '@polkadot/wasm-crypto-wasm/$1.js',
    '^@polkadot/wasm-crypto-wasm$': '@polkadot/wasm-crypto-wasm/data.js',
    '^@polkadot/x-global$': '@polkadot/x-global/index.js',
    '^@polkadot/x-randomvalues$': '@polkadot/x-randomvalues/node.js',
    '^@polkadot/x-textdecoder$': '@polkadot/x-textdecoder/node.js',
    '^@polkadot/x-textencoder$': '@polkadot/x-textencoder/node.js',
    '^@polkadot/x-bigint/(.*)': '@polkadot/x-bigint/$1.js',
    '^@polkadot/x-bigint$': '@polkadot/x-bigint/index.js',
    '^@polkadot/x-noble-secp256k1$': '@polkadot/x-noble-secp256k1/index.js',
    '^@polkadot/x-noble-hashes/(.*)': '@polkadot/x-noble-hashes/$1.js',
    '^@polkadot/x-noble-hashes$': '@polkadot/x-noble-hashes/index.js',
    '^@polkadot/x-ws$': '@polkadot/x-ws/node.js',
    '^@polkadot/x-fetch$': '@polkadot/x-fetch/node.js',
  },
  transformIgnorePatterns: [
    '/node_modules/(?!@polkadot|@webb-tools|@babel/runtime/helpers/esm/)',
  ],
  moduleDirectories: ['node_modules'],
};
```

> Another hack/workaround in a normal javascript developer day.
