### ISSUE TITLE
Webpack4 and @polkadot/x-textdecoder: TextEncoder is not a constructor

### ISSUE THREAD

**Issue by nepoche** [polkadot-js/common#1441]
I am in the process of updating an application created with create-react-app. I understand there are some limitations around webpack4 and polkadot dependencies - but from what I have seen, these issues are related to `import.meta` syntax and issues with transpiled code.

My code and configuration seems to work with:
- @polkadot/api: 6.12.1
- @polkadot/dev: 0.61.31
- @polkadot/utils: 8.2.2

While updating the dependencies to the following:
- @polkadot/api: 7.13.1
- @polkadot/dev: 0.65.90
- @polkadot/utils: 8.6.1

I encounter the following issue:

```
Uncaught TypeError: _polkadot_x_textencoder__WEBPACK_IMPORTED_MODULE_0__.TextEncoder is not a constructor
    at Module.../../node_modules/@polkadot/util/string/toU8a.js (toU8a.js:4:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/u8a/toU8a.js (toU8a.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/u8a/cmp.js (cmp.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/u8a/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/bi/toHex.js (toHex.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/bi/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/bundle.js (bundle.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Module.../../node_modules/@polkadot/util/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:926:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (web3-mixer-deposit.ts:13:1)
    at Object.../react-environment/src/api-providers/web3/web3-mixer-deposit.ts (web3-mixer-deposit.ts:19:1)
```

This is the line of code which is failing:
`import { u8aToHex } from '@polkadot/util';`

Are there any known webpack configurations that are needed to make @polkadot dependencies work with webpack4? Besides the one listed for the `import.meta` [problem](https://polkadot.js.org/docs/usage/FAQ#on-webpack-4-i-have-a-parse-error-on-importmetaurl)

**Comment by jacogr** [comment]
Just ran the above with (bit more complex, I used an existing project) -

```js
import { ApiPromise, WsProvider, packageInfo } from '@polkadot/api';
import { u8aToHex } from '@polkadot/util';

console.log(packageInfo);

async function main () {
	console.log(u8aToHex(new Uint8Array([1, 2, 3])));

	const api = await ApiPromise.create({
		provider: new WsProvider('wss://rpc.polkadot.io')
	});

	api.derive.chain.bestNumber((n) => {
		const div = document.createElement('div');

		div.appendChild(document.createTextNode(n.toHuman()));
		document.getElementById("root").appendChild(div);
	});
}

main().catch(console.error);
````

and

```js
const path = require('path');

module.exports = {
  entry: ['regenerator-runtime/runtime', './index.js'],
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: require.resolve('@open-wc/webpack-import-meta-loader'),
      },
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env']
          }
        }
      }
    ]
  }
};
```

And all ok.
