### ISSUE TITLE
when require("nem-library") , keyring.addFromUri error

### ISSUE THREAD

**Issue by wmvm0** [polkadot-js/common#1571]
When add  require("nem-library") in the unit test file suri.spec.ts, the keyring.addFromUri method throws an exception

but I need the nem-library。

Maybe nem-library affecting keyring.addFromUri normal work, I haven't found the reason. Could you please take a look ？
```
require("nem-library")

describe('keyring.addFromUri', (): void => {
  Object.entries(TESTS).forEach(([type, tests]): void => {
    const keyring = new Keyring({ type: type as KeypairType });

    beforeEach(async (): Promise<void> => {
      await cryptoWaitReady();
    });

    describe(type, (): void => {
      tests.forEach(({ pk, ss, uri }): void => {
        it(`creates ${uri}`, (): void => {
          const pair = keyring.addFromUri(uri, {}, type as KeypairType);

          expect(u8aToHex(pair.publicKey)).toEqual(pk);
          expect(pair.address).toEqual(ss);
        });
      });
    });
  });
});
```

error:
```
Error: Expected a seed matching 32 bytes, found 0

    at sr25519PairFromSeed (/Users/admin/code/bibox/node_lib/common/packages/util-crypto/src/sr25519/pair/fromSeed.ts:20:11)
    at Object.sr25519 (/Users/admin/code/bibox/node_lib/common/packages/keyring/src/keyring.ts:18:43)
    at Keyring.createFromUri (/Users/admin/code/bibox/node_lib/common/packages/keyring/src/keyring.ts:240:21)
    at Keyring.createFromUri [as addFromUri] (/Users/admin/code/bibox/node_lib/common/packages/keyring/src/keyring.ts:158:12)
    at Object.addFromUri (/Users/admin/code/bibox/node_lib/common/packages/keyring/src/suri.spec.ts:103:32)
    at Promise.then.completed (/Users/admin/code/bibox/node_lib/common/node_modules/jest-circus/build/utils.js:333:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/Users/admin/code/bibox/node_lib/common/node_modules/jest-circus/build/utils.js:259:10)
    at _callCircusTest (/Users/admin/code/bibox/node_lib/common/node_modules/jest-circus/build/run.js:277:40)
    at _runTest (/Users/admin/code/bibox/node_lib/common/node_modules/jest-circus/build/run.js:209:3)


```

**Comment by jacogr** [comment]
Looking at the library - https://www.npmjs.com/package/nem-library - 

- it is not being maintained anymore
- there is no source for this library to look at - this 404's https://github.com/aleixmorgadas/nem-library-ts as does this 
- there is no place to log issues against this or look at this

So I really cannot comment on this, nor investigate. 

Sorry, but I don't even have a suggestion for you to look at, this is the ultimate black-box request.

**Comment by wmvm0** [comment]
ok, thanks. I find another solution.

**Comment by wmvm0** [comment]
> Looking at the library - https://www.npmjs.com/package/nem-library -
> 
> * it is not being maintained anymore
> * there is no source for this library to look at - this 404's https://github.com/aleixmorgadas/nem-library-ts
> * there is no place to log issues against this or look at this
> 
> So I really cannot comment on this, nor investigate.
> 
> Sorry, but I don't even have a suggestion for you to look at, this is the ultimate black-box request.

ok, thanks. I try to find other solution.

**Comment by wmvm0** [comment]
I found where it affects, but I don't know why, you can look at the issue https://github.com/QuantumMechanics/NEM-sdk/issues/77

**Comment by wmvm0** [comment]
resolve
