### ISSUE TITLE
schnorrkel polyfill breaks test

### ISSUE THREAD

**Issue by tjwelde** [polkadot-js/common#321]
We are testing our application with jest.
After updating the polkadot api, we couldn't run our tests anymore, because of following error:

```
TypeError: Object.defineProperty called on non-object
        at Function.defineProperty (<anonymous>)

      at Object.<anonymous> (../node_modules/@polkadot/util-crypto/schnorrkel/schnorrkel-js/polyfill.js:9:10)
      at Object.<anonymous> (../node_modules/@polkadot/util-crypto/schnorrkel/schnorrkel-js/index.js:11:1)
      at Object.<anonymous> (../node_modules/@polkadot/util-crypto/schnorrkel/keypair/fromSeed.js:10:42)
```

The line failing is:

https://github.com/polkadot-js/common/blob/98e2964c73f02cd49e91dc654d9eb8795b8d8dd1/packages/util-crypto/src/schnorrkel/schnorrkel-js/polyfill.ts#L8

We circumvent the problem right now, by setting the node_env to another value for our tests.

**Comment by jacogr** [comment]
Ok, that is not good and should not have made it in - it is a specific local polyfill, not a "deploy with this".

**Comment by jacogr** [comment]
PR to api to follow as soon as CI deployment is done.
