### ISSUE TITLE
Unable to sign message using schnorrkelSign

### ISSUE THREAD

**Issue by ansonla3** [polkadot-js/common#438]
```
const { schnorrkelKeypairFromSeed, schnorrkelSign, schnorrkelVerify, naclVerify } = require('@polkadot/util-crypto');
  
(async () => {
  const signResult = await schnorrkelSign("bboy",
  {"publicKey": "5HMn1X3wTggh5cbPpXUYMhkktkuMxk8J",
   "secretKey": "7206bdad12b550caa0083a73ecba7ab2b75524d31d0c2ea0b97321da3a26d7b4"
  })
}) ()
```

Result
```
 node index.js
(node:8134) UnhandledPromiseRejectionWarning: ExtError: @polkadot/wasm-crypto has not been initialized
    at assert (/Users/anson/test-sign/node_modules/@polkadot/util/assert.js:47:9)
    at params (/Users/anson/test-sign/node_modules/@polkadot/wasm-crypto/index.js:12:5)
    at schnorrkelSign (/Users/anson/test-sign/node_modules/@polkadot/util-crypto/schnorrkel/sign.js:30:38)
    at /Users/anson/test-sign/index.js:4:28
    at Object.<anonymous> (/Users/anson/test-sign/index.js:8:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
node version: v10.16
util-crypto:  ^0.93.1

**Comment by jacogr** [comment]
Ok, was out today - seeing this now. So you need to init WASM, 

`await cryptoWaitReady()`
