### ISSUE TITLE
API/INIT: Capabilities detected: {"AccountInfo":"AccountInfoWithProviders","ValidatorPrefs":"ValidatorPrefsWithBlocked"}

### ISSUE THREAD

**Issue by ksr30** [polkadot-js/common#852]
hey everyone,
I am getting this error while using polkadot-js
```
(node:18953) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'create' of undefined
    at polkadex_market_data (/home/ubuntu/Polkadex/load-tester/simulate-trades.js:222:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
(node:18953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-01-22 07:31:11        API/INIT: Capabilities detected: {"AccountInfo":"AccountInfoWithProviders","ValidatorPrefs":"ValidatorPrefsWithBlocked"}
```
any clue?

**Comment by jacogr** [comment]
The error is the following -

```
Cannot read property 'create' of undefined
    at polkadex_market_data (/home/ubuntu/Polkadex/load-tester/simulate-trades.js:222:31)
    ```
    
So in line 222 of `simulate-trades.js` `.create` is called on something that does not exist.
